[env]
WINIT_UNIX_BACKEND = "wayland"

[window]
padding.x = 12
padding.y = 12
decorations = "full"
opacity = 0.90

[font]
size = 11.0

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[colors]
primary.background = "#1e1e2e"
primary.foreground = "#cdd6f4"

cursor.cursor = "#f5e0dc"
cursor.text = "#1e1e2e"

selection.background = "#585b70"
selection.text = "#cdd6f4"

normal.black = "#45475a"
normal.red = "#f38ba8"
normal.green = "#a6e3a1"
normal.yellow = "#f9e2af"
normal.blue = "#89b4fa"
normal.magenta = "#f5c2e7"
normal.cyan = "#94e2d5"
normal.white = "#bac2de"

bright.black = "#a6adc8"
bright.red = "#f38ba8"
bright.green = "#a6e3a1"
bright.yellow = "#f9e2af"
bright.blue = "#89b4fa"
bright.magenta = "#f5c2e7"
bright.cyan = "#94e2d5"
bright.white = "#cdd6f4"

[scrolling]
multiplier = 3

[mouse]
hide_when_typing = true
